# Generated by Django 4.1.7 on 2023-03-13 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0002_alter_note_body"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="slug",
            field=models.SlugField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
